# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  statuses: write
  checks: write

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.3.3
      with:
        arguments: desktop:dist
    
    - name: Log Checkstyle Report as Annotations
      uses: kiancross/checkstyle-annotations-action@v1

    - name: Test & CheckStyle
      uses: gradle/gradle-build-action@v2.3.3
      with:
        arguments: check
        
    - name: Report Test
      uses: dorny/test-reporter@v1.6.0
      if: always()
      with:
        name: Test Report
        path: tests/build/test-results/test/*.xml
        reporter: java-junit
        fail-on-error: true
        
    - name: Report Code Coverage
      uses: PavanMudigonda/jacoco-reporter@v4.8
      with:
        coverage_results_path: tests/build/jacoco.xml
        coverage_report_name: Coverage
        coverage_report_title: JaCoCo
        github_token: ${{ secrets.GITHUB_TOKEN }}
        skip_check_run: false
        minimum_coverage: 80
        fail_below_threshold: false
        publish_only_summary: false
      
    - name: Upload game JAR
      uses: actions/upload-artifact@v3.1.2
      with:
        name: piazza-panic
        path: desktop/build/libs/desktop-1.0.jar
      
